name: Delete deployed environment

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
        description: AWS Access Key Id
      AWS_SECRET_ACCESS_KEY:
        required: true
        description: AWS Secret Access Key
      KUBECONFIG:
        required: true
        description: Kubernetes Configuration

jobs:
  delete-env:
    runs-on: ubuntu-24.04
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v4

      - name: "Environment: feature"
        run: |
          # convert to lower case
          HEAD_BRANCH_LOWERCASE=${GITHUB_HEAD_REF,,}

          # substitute all non-alphanumeric chars with hyphens "-"
          HEAD_BRANCH_LOWERCASE_NO_NONALPHANUMERIC=${HEAD_BRANCH_LOWERCASE//[^[:alnum:]]/-}

          # trim to 25 chars, in order to fit into the 53 char Helm release name limit
          # the rest of the chars up to the limit are saved for the static part of the release names
          SANITIZED_HEAD_BRANCH=${HEAD_BRANCH_LOWERCASE_NO_NONALPHANUMERIC::25}

          echo "ENVIRONMENT=$SANITIZED_HEAD_BRANCH" >> $GITHUB_ENV
          echo "CLASSIFICATION=feature" >> $GITHUB_ENV

      - name: Setup aws-iam-authenticator
        uses: prepor/action-aws-iam-authenticator@master

      - name: Check aws-iam-authenticator version
        run: aws-iam-authenticator version

      - name: Configure kubectl
        run: |
          mkdir $PWD/.kube
          echo "${{ secrets.KUBECONFIG }}" > $PWD/.kube/config
          echo "KUBECONFIG=$PWD/.kube/config" >> $GITHUB_ENV

      - name: Setup Sops
        uses: mdgreenwald/mozilla-sops-action@v1.6.0

      - name: Setup helm secrets plugin
        run: helm plugin install https://github.com/jkroepke/helm-secrets --version v3.8.3

      - name: Setup Skaffold
        run: |
          wget https://storage.googleapis.com/skaffold/releases/${VERSION}/${BINARY} -O ./skaffold
          chmod +x ./skaffold
        env:
          VERSION: v2.6.0
          BINARY: skaffold-linux-amd64

      - name: Delete environment
        run: |
          SKAFFOLD_PROFILE=$([ "$CLASSIFICATION" == "feature" ] && echo "dev" || echo "$CLASSIFICATION")

          ./skaffold delete --profile $SKAFFOLD_PROFILE
        env:
          KUBECONFIG: ${{ env.KUBECONFIG }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
